steps:

## Go build produces binary
##   /workspace/yvr-io/gopath/bin/yvr-io
##
## Docker Image build copies
##  - Certs
##  - /workspace/yvr-io/gopath/bin/yvr-io -> /yvr-io
##
## Use dir: because we are not at the root of the git repo.
##  `dir: yvr-io`
##

#CGO_ENABLED=0 go build -a -installsuffix cgo
- name: 'gcr.io/cloud-builders/go'
  env:
  - PROJECT_ROOT=yvr-io
  - CGO_ENABLED=0
  args:
    - 'install'
    - '-a'
    - '-installsuffix'
    - 'cgo'
    - '.'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  id: 'write'
  args:
  - '-c'
  - |
    cp /etc/ssl/certs/ca-certificates.crt .

    cat > Dockerfile <<EOS
    FROM scratch
    ADD ca-certificates.crt /etc/ssl/certs/
    ADD gopath/bin/yvr-io /
    CMD ["/yvr-io"]
    EOS

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/yvr-io/hello:$SHORT_SHA', '.']

images: ['gcr.io/yvr-io/hello:$SHORT_SHA']